name: nordmart-review-test

on: push

env:
  URL: "bilalbokharee/gitops-config-template"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOCKER_FILE_PATH: Dockerfile
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: bilalbokharee
  IMAGE_NAME: nordmart-test
  IMAGE_TAGS: 0.0.1

jobs:
  # update-versions:
  #   name: Update Versions
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #       with:
  #         repository: "bilalbokharee/gitops-config-template"
  #         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
  #         fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      
  #     - name: Install SSH Client 🔑
  #       uses: webfactory/ssh-agent@v0.4.0
  #       with:
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #     - run: |
  #         ls 
  #         pwd
  #         GENERATED_TAG="$(git rev-parse --short HEAD)"
  #         yq -i '.dependencies[0].version = "0.0.0"' 01-gabbar/apps/01-stakater-nordmart-review/01-dev/Chart.yaml
  #         yq -i '.version = "0.0.0"' 01-gabbar/apps/01-stakater-nordmart-review/01-dev/Chart.yaml 
  #         yq -i '.sample-app-helm.application.deployment.image.tag = "0.0.0"' 01-gabbar/apps/01-stakater-nordmart-review/01-dev/values.yaml
  #         echo "File updated"
  #       name: 'Update Chart'
    
    

  #     # Commit back chang
  #     - name: Commit files
  #       run: |
  #         git config --local user.email "github-root@stakater.com"
  #         git config --local user.name "stakater-github-root"
  #         git status
  #         git diff
  #         git add .
  #         git commit -m "[skip-ci] Update artifacts" -a

  #     - name: Deploy 🚀
  #       uses: JamesIves/github-pages-deploy-action@v4.2.5
  #       with:
  #         ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         repository-name: "bilalbokharee/gitops-config-template"
  #         branch: main
  #         target-folder: "01-gabbar/apps/01-stakater-nordmart-review/01-dev"
  #         folder: "01-gabbar/apps/01-stakater-nordmart-review/01-dev"

  login-and-push:
    name: Login and push image to Quay.io
    runs-on: ubuntu-20.04

    steps:

      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2


      - name: Generate Tag
        id: generate_tag
        uses: anothrNick/github-tag-action@1.38.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          DRY_RUN: true

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          layers: false
          tags: ${{ steps.generate_tag.outputs.new_tag }}
          dockerfiles: |
            ./Dockerfile
      # Authenticate to container image registry to push the image
      - name: Podman Login
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: bilalbokharee+ramesses
          password: ${{ secrets.QUAY_ROBOT }}

      # Push the image to Quay.io (Image Registry)
      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          # extra-args: |
          #   --disable-content-trust
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
