name: nordmart-review-test

on: push

env:
  URL: "bilalbokharee/gitops-config-template"
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  update-versions:
    name: Update Versions
    runs-on: ubuntu-latest #stakater/pipeline-toolbox:v0.0.2
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: "bilalbokharee/gitops-config-template"
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      # - name: Generate Tag
      #   id: generate_tag
      #   uses: anothrNick/github-tag-action@1.26.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITOPS_GITHUB_TOKEN }}
      #     WITH_V: false
      #     DEFAULT_BUMP: patch
      #     DRY_RUN: true

      - run: |
          ls 
          pwd
          GENERATED_TAG="$(git rev-parse --short HEAD)"
          yq -i '.dependencies[0].version = "0.0.0"' 01-gabbar/apps/01-stakater-nordmart-review/01-dev/Chart.yaml
          yq -i '.version = "0.0.0"' 01-gabbar/apps/01-stakater-nordmart-review/01-dev/Chart.yaml 
          yq -i '.sample-app-helm.application.deployment.image.tag = "0.0.0"' 01-gabbar/apps/01-stakater-nordmart-review/01-dev/values.yaml
          echo "File updated"
        name: 'Update Chart'
    
    

      # Commit back chang
      - name: Commit files
        run: |
          git config --local user.email "github-root@stakater.com"
          git config --local user.name "stakater-github-root"
          git status
          git diff
          git add .
          git commit -m "[skip-ci] Update artifacts" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPLOY_KEY }}
          repository: "bilalbokharee/gitops-config-template"
          branch: main